module mFN1
implicit none
contains

attributes(host,device) FUNCTION FN1(XDUMM)
      use glibc_exp_mod, only: myexp
      IMPLICIT NONE
      DOUBLE PRECISION FN1, XDUMM, F00X
      F00X=myexp(-XDUMM)
      FN1=(1.d0-F00X)
      FN1=FN1+(-F00X*XDUMM)
      FN1=FN1+(-F00X*XDUMM**2/2.d0)
      FN1=FN1+(-F00X*XDUMM**3/6.d0)
      FN1=FN1+(-F00X*XDUMM**4/24.d0)
      FN1=FN1+(-F00X*XDUMM**5/120.d0)
      FN1=FN1+(-F00X*XDUMM**6/720.d0)
      END FUNCTION FN1

end module mFN1
