# Makefile for CUDA GPU compilation using nvfortran (NVIDIA HPC SDK)
FC      = mpif90
CUDA_HOME = /opt/nvidia/hpc_sdk/Linux_x86_64/24.1/cuda
FFLAGS    = -O2 -tp=native -cuda -gpu=cc89
CUDALIBS = -L$(CUDA_HOME)/lib64 -lcudart
MPILIBS   = -lmpi
LDFLAGS   = -llapack -lblas

.SUFFIXES:
.SUFFIXES: .f90 .f .cuf .o

.f90.o:
	$(FC) $(FFLAGS) -c $<

.f.o:
	$(FC) $(FFLAGS) -c $<

.cuf.o:
	$(FC) $(FFLAGS) -c $<

OBJECTS=\
 qmccluster.o\
 mmontecarlo.o\
 mminimiza.o\
 mentradatos.o\
 mconfiguraciones.o\
 mparametros.o\
 mrandom.o\
 mrandom2.o\
 mtipos.o\
 mdensidades.o\
 dmc_gpu_params.o\
 dmc_gpu.o\
 wf_gpu.o\
 msteps.o\
 mwavef.o\
 mangwavef.o\
 mimagina.o\
 mrotaciones.o\
 msistref.o\
 mvaziz.o\
 mvmolecula.o\
 mmcvpromedia.o\
 mdmcpromedia.o\
 bh_heh2m.o\
 pw_heocs.o\
 mhh_heocs.o\
 mkp_heco.o\
 kpcoef.o\
 mlineal.o\
 mlegendre.o\
 modlegendre.o\

qmccluster: $(OBJECTS) mmpi.o
	$(FC) $(FFLAGS) -o $@ $^ $(LDFLAGS) $(MPILIBS) $(CUDALIBS)

clean:
	rm -f qmccluster *.o *.d *.mod work.pc work.pcl tags

# -----------------------------------------------------------------------
# Dependencias modulos base
# -----------------------------------------------------------------------
mparametros.o: mparametros.f90
mrandom2.o: mrandom2.f90
mrandom.o: mrandom.f90 mrandom2.o
mtipos.o: mtipos.f90
mvaziz.o: mvaziz.f90
mlineal.o: mlineal.f90
mlegendre.o: mlegendre.f90
modlegendre.o: modlegendre.f
bh_heh2m.o: bh_heh2m.f
pw_heocs.o: pw_heocs.f
kpcoef.o: kpcoef.f
	$(FC) $(FFLAGS) -c $< $(LDFLAGS)

mrotaciones.o: mrotaciones.f90 mtipos.o
msistref.o: msistref.f90 mparametros.o mtipos.o
mangwavef.o: mangwavef.f90 mparametros.o mtipos.o mlegendre.o
mimagina.o: mimagina.f90 mtipos.o mlegendre.o
mvmolecula.o: mvmolecula.f90 pw_heocs.o mhh_heocs.o mkp_heco.o
mhh_heocs.o: mhh_heocs.f90 mparametros.o mtipos.o bh_heh2m.o
mkp_heco.o: mkp_heco.f90 mparametros.o mtipos.o
mmcvpromedia.o: mmcvpromedia.f90 mtipos.o mdensidades.o
mdmcpromedia.o: mdmcpromedia.f90 mtipos.o
mdensidades.o: mdensidades.f90 msistref.o mparametros.o mtipos.o
mentradatos.o: mentradatos.f90 mparametros.o mvaziz.o bh_heh2m.o \
               pw_heocs.o mhh_heocs.o mkp_heco.o mrandom.o
mconfiguraciones.o: mconfiguraciones.f90 mrandom.o

# -----------------------------------------------------------------------
# Modulos GPU
# -----------------------------------------------------------------------
dmc_gpu_params.o: dmc_gpu_params.cuf mparametros.o mtipos.o mvaziz.o
dmc_gpu.o: dmc_gpu.cuf dmc_gpu_params.o

# -----------------------------------------------------------------------
# Modulos GPU
# -----------------------------------------------------------------------
wf_gpu.o: wf_gpu.cuf dmc_gpu_params.o

# -----------------------------------------------------------------------
# Modulos que usan GPU
# -----------------------------------------------------------------------
mwavef.o: mwavef.f90 mparametros.o mtipos.o mangwavef.o mrotaciones.o \
          msistref.o mvaziz.o mvmolecula.o bh_heh2m.o mlineal.o wf_gpu.o

msteps.o: msteps.f90 mparametros.o mtipos.o mrandom.o mwavef.o \
          mrotaciones.o mmcvpromedia.o

mmontecarlo.o: mmontecarlo.f90 mparametros.o mconfiguraciones.o mtipos.o \
               msteps.o mwavef.o msistref.o mkp_heco.o mdensidades.o    \
               mimagina.o mmcvpromedia.o mdmcpromedia.o mrandom.o mmpi.o \
               dmc_gpu_params.o

mminimiza.o: mminimiza.f90 mmontecarlo.o mentradatos.o mparametros.o mmpi.o

qmccluster.o: qmccluster.f90 mmontecarlo.o mminimiza.o mentradatos.o \
              mparametros.o mmpi.o

mmpi.o: mmpi.f90 mtipos.o mrandom.o mrandom2.o mvaziz.o mvmolecula.o \
        mparametros.o
	$(FC) -I. $(FFLAGS) -c $< $(MPILIBS)