module mccuerpo
 use mtipos, only: vec3
 implicit none
 integer, private, parameter :: i4 = selected_int_kind(9)
 integer, private, parameter :: r8 = selected_real_kind(15,9)
 integer(kind=i4), device :: ngatom, natom

contains

attributes(host, device) subroutine ccuerpo(atom, sprop, rhesal)
  type(vec3), intent (in)  :: atom(natom), sprop(3)
  real(kind=r8), intent (out) :: rhesal(3*ngatom)
  type(vec3) :: rtemp
  integer(kind=i4) :: iatom,jatom,ic,jc

    iatom=0
      do jatom=1,ngatom
          rtemp%comp = atom(jatom)%comp - atom(natom)%comp
         do ic=1,3
           rhesal(iatom+ic)=0.0_r8
           do jc=1,3
             rhesal(iatom+ic)=rhesal(iatom+ic)+sprop(ic)%comp(jc)*rtemp%comp(jc)
           enddo
         enddo
         iatom=iatom+3
      enddo

 end subroutine ccuerpo

attributes(global) subroutine k_ccuerpo(n, atom, sprop, rhesal)
  integer(kind=i4), value :: n
  type(vec3), device, intent (in)  :: atom(natom,n), sprop(3,n)
  real(kind=r8), device, intent (out) :: rhesal(3*ngatom,n)
  integer(kind=i4) :: i

  i = (blockIdx%x - 1) * blockDim%x + threadIdx%x
  if (i <= n) then
    call ccuerpo(atom(:,i), sprop(:,i), rhesal(:,i))
  endif
end subroutine k_ccuerpo

end module mccuerpo
