# Makefile.cuda -- Original-CUDA con verificacion GPU (opcion=5)
# Uso: make -f Makefile.cuda
#
# Requiere NVIDIA HPC SDK con nvfortran como compilador base de mpif90.
# El flag -cuda activa CUDA Fortran; los .cuf se compilan igual que los .f90.

HPC_SDK   = /opt/nvidia/hpc_sdk/Linux_x86_64/24.1
FC        = $(HPC_SDK)/comm_libs/openmpi4/bin/mpif90
CUDA_HOME = $(HPC_SDK)/cuda
FFLAGS    = -O2 -tp=native -cuda -gpu=cc89
# Para ver info de registros/spilling por kernel:
# FFLAGS  = -O2 -tp=native -cuda -gpu=cc89 -Minfo=accel
# Para depuracion:
# FFLAGS  = -O0 -g -cuda -gpu=cc89 -Minfo=accel

CUDALIBS  = -L$(CUDA_HOME)/lib64 -lcudart
MPILIBS   = -lmpi
LDFLAGS   = -llapack -lblas

.SUFFIXES:
.SUFFIXES: .f90 .f .cuf .o

.f90.o:
	$(FC) $(FFLAGS) -c $<

.f.o:
	$(FC) $(FFLAGS) -c $<

.cuf.o:
	$(FC) $(FFLAGS) -c $<

OBJECTS=\
 qmccluster.o\
 mmontecarlo.o\
 mminimiza.o\
 mentradatos.o\
 mconfiguraciones.o\
 mparametros.o\
 mrandom.o\
 mrandom2.o\
 mtipos.o\
 mdensidades.o\
 mderwavefm_gpu.o\
 mwavefm_gpu.o\
 mwavefhe4_gpu.o\
 mwavefhe3_gpu.o\
 mwavefx_gpu.o\
 mwavef_gpu.o\
 mderwavefhe3_gpu.o\
 mderwavefx_gpu.o\
 mderananum_gpu.o\
 mbhutils_gpu.o\
 mccuerpo_gpu.o\
 mpotenbh_gpu.o\
 mhedihydrogen_gpu.o\
 mvalibre_gpu.o\
 mvpot_gpu.o\
 mgauss3_gpu.o\
 mrota_gpu.o\
 mhpsi_gpu.o\
 mdmc2_gpu.o\
 mtest_gpu.o\
 msteps.o\
 mwavef.o\
 mangwavef.o\
 mimagina.o\
 mrotaciones.o\
 msistref.o\
 mvaziz.o\
 mvmolecula.o\
 mmcvpromedia.o\
 mdmcpromedia.o\
 bh_heh2m.o\
 pw_heocs.o\
 mhh_heocs.o\
 mkp_heco.o\
 kpcoef.o\
 mlineal.o\
 mlegendre.o\
 modlegendre.o\

qmccluster: $(OBJECTS) mmpi.o
	$(FC) $(FFLAGS) -o $@ $^ $(LDFLAGS) $(MPILIBS) $(CUDALIBS)

clean:
	rm -f qmccluster *.o *.d *.mod work.pc work.pcl tags

# -----------------------------------------------------------------------
# Modulos base (sin GPU) -- igual que Makefile.mpi
# -----------------------------------------------------------------------
mparametros.o: mparametros.f90

mrandom2.o: mrandom2.f90

mrandom.o: mrandom.f90 mrandom2.o

mtipos.o: mtipos.f90

mvaziz.o: mvaziz.f90

mlineal.o: mlineal.f90

mlegendre.o: mlegendre.f90

modlegendre.o: modlegendre.f

bh_heh2m.o: bh_heh2m.f

pw_heocs.o: pw_heocs.f

kpcoef.o: kpcoef.f
	$(FC) $(FFLAGS) -c $< $(LDFLAGS)

mrotaciones.o: mrotaciones.f90 mtipos.o

msistref.o: msistref.f90 mparametros.o mtipos.o

mangwavef.o: mangwavef.f90 mparametros.o mtipos.o mlegendre.o

mimagina.o: mimagina.f90 mtipos.o mlegendre.o

mvmolecula.o: mvmolecula.f90 pw_heocs.o mhh_heocs.o mkp_heco.o

mhh_heocs.o: mhh_heocs.f90 modlegendre.o

mkp_heco.o: mkp_heco.f90 kpcoef.o

mmcvpromedia.o: mmcvpromedia.f90 mtipos.o mdensidades.o

mdmcpromedia.o: mdmcpromedia.f90 mtipos.o

mdensidades.o: mdensidades.f90 msistref.o mparametros.o mtipos.o

mentradatos.o: mentradatos.f90 mparametros.o mvaziz.o bh_heh2m.o \
               pw_heocs.o mhh_heocs.o mkp_heco.o mrandom.o

mconfiguraciones.o: mconfiguraciones.f90 mrandom.o

mwavef.o: mwavef.f90 mparametros.o mtipos.o mangwavef.o mrotaciones.o \
          msistref.o mvaziz.o mvmolecula.o bh_heh2m.o mlineal.o

msteps.o: msteps.f90 mparametros.o mtipos.o mrandom.o mwavef.o \
          mrotaciones.o mmcvpromedia.o

# -----------------------------------------------------------------------
# Modulos GPU (.cuf) -- orden: mderwavefm_gpu antes que mtest_gpu
# -----------------------------------------------------------------------
mderwavefm_gpu.o: mderwavefm_gpu.cuf mparametros.o mtipos.o

mwavefm_gpu.o: mwavefm_gpu.cuf mparametros.o mtipos.o

mwavefhe4_gpu.o: mwavefhe4_gpu.cuf mparametros.o mtipos.o

mwavefhe3_gpu.o: mwavefhe3_gpu.cuf mparametros.o mtipos.o

mwavefx_gpu.o: mwavefx_gpu.cuf mparametros.o mtipos.o

mwavef_gpu.o: mwavef_gpu.cuf mparametros.o mtipos.o

mderwavefhe3_gpu.o: mderwavefhe3_gpu.cuf mparametros.o mtipos.o

mderwavefx_gpu.o: mderwavefx_gpu.cuf mparametros.o mtipos.o

mderananum_gpu.o: mderananum_gpu.cuf mparametros.o mtipos.o

mbhutils_gpu.o: mbhutils_gpu.cuf mparametros.o mtipos.o

mccuerpo_gpu.o: mccuerpo_gpu.cuf mparametros.o mtipos.o

mpotenbh_gpu.o: mpotenbh_gpu.cuf mparametros.o mtipos.o

mhedihydrogen_gpu.o: mhedihydrogen_gpu.cuf mparametros.o mtipos.o msistref.o

mvalibre_gpu.o: mvalibre_gpu.cuf mparametros.o mtipos.o

mvpot_gpu.o: mvpot_gpu.cuf mparametros.o mtipos.o msistref.o mvaziz.o

mgauss3_gpu.o: mgauss3_gpu.cuf mrandom2.o

mrota_gpu.o: mrota_gpu.cuf mparametros.o mtipos.o

mhpsi_gpu.o: mhpsi_gpu.cuf mderananum_gpu.o mvpot_gpu.o mvalibre_gpu.o

mdmc2_gpu.o: mdmc2_gpu.cuf mhpsi_gpu.o mgauss3_gpu.o mrota_gpu.o \
             mderananum_gpu.o mvpot_gpu.o

mtest_gpu.o: mtest_gpu.cuf mparametros.o mtipos.o mwavef.o msistref.o \
             mderwavefm_gpu.o mwavefm_gpu.o mwavefhe4_gpu.o \
             mwavefhe3_gpu.o mwavefx_gpu.o mwavef_gpu.o \
             mderwavefhe3_gpu.o mderwavefx_gpu.o mderananum_gpu.o \
             mvalibre_gpu.o mvpot_gpu.o \
             mbhutils_gpu.o mccuerpo_gpu.o mpotenbh_gpu.o \
             mhedihydrogen_gpu.o mvalibre_gpu.o mvpot_gpu.o \
             mgauss3_gpu.o mrota_gpu.o mhpsi_gpu.o mdmc2_gpu.o \
             bh_heh2m.o

# -----------------------------------------------------------------------
# Modulos que usan GPU
# -----------------------------------------------------------------------
mmontecarlo.o: mmontecarlo.f90 mparametros.o mconfiguraciones.o mtipos.o \
               msteps.o mwavef.o msistref.o mkp_heco.o mdensidades.o    \
               mimagina.o mmcvpromedia.o mdmcpromedia.o mrandom.o mmpi.o \
               mtest_gpu.o mderwavefm_gpu.o

mminimiza.o: mminimiza.f90 mmontecarlo.o mentradatos.o mparametros.o mmpi.o

qmccluster.o: qmccluster.f90 mmontecarlo.o mminimiza.o mentradatos.o \
              mparametros.o mmpi.o

mmpi.o: mmpi.f90 mtipos.o mrandom.o mrandom2.o mvaziz.o mvmolecula.o \
        mparametros.o
	$(FC) -I. $(FFLAGS) -c $< $(MPILIBS)
