#FC=mpiifx
FFLAGS=-O2
FC=mpif90
#F77FLAGS= -extend-source 132 -O2
#LDFLAGS= -L/usr/lib64 -llapack -lblas
MPILIBS= -lmpi
LDFLAGS= -llapack -lblas
#LDFLAGS= -L/usr/lib64 -llapack -lblas


.SUFFIXES:
.SUFFIXES: .f90 .f .o

.f90.o:
	$(FC) $(FFLAGS) -c $<

.f.o:
	$(FC) $(FFLAGS) -c $<

OBJECTS=\
 qmccluster.o\
 mmontecarlo.o\
 mminimiza.o\
 mentradatos.o\
 mconfiguraciones.o\
 mparametros.o\
 mrandom.o\
 mrandom2.o\
 mtipos.o\
 mdensidades.o\
 msteps.o\
 mwavef.o\
 mangwavef.o\
 mimagina.o\
 mrotaciones.o\
 msistref.o\
 mvaziz.o\
 mvmolecula.o\
 mmcvpromedia.o\
 mdmcpromedia.o\
 bh_heh2m.o\
 pw_heocs.o\
 mhh_heocs.o\
 mkp_heco.o\
 kpcoef.o\
 mlineal.o\
 mlegendre.o\
 modlegendre.o\

SRC=\
 qmccluster.f90\
 mmontecarlo.f90\
 mminimiza.f90\
 mentradatos.f90\
 mconfiguraciones.f90\
 mparametros.f90\
 mrandom.f90\
 mrandom2.f90\
 mtipos.f90\
 mdensidades.f90\
 msteps.f90\
 mwavef.f90\
 mangwavef.f90\
 mimagina.f90\
 mrotaciones.f90\
 msistref.f90\
 mvaziz.f90\
 mvmolecula.f90\
 mmcvpromedia.f90\
 mdmcpromedia.f90\
 bh_heh2m.f\
 pw_heocs.f\
 mhh_heocs.f90\
 mkp_heco.f90\
 kpcoef.f\
 mlineal.f90\
 mlegendre.f90\
 modlegendre.f\
 mmpi.f90\

qmccluster: $(OBJECTS) mmpi.o
	$(FC) $(FFLAGS) -o $@ $^ $(LDFLAGS) $(MPILIBS)


clean:
	rm -f *\.o *\.d work.pc work.pcl tags *\.mod

qmccluster.o: qmccluster.f90 mmontecarlo.o mminimiza.o mentradatos.o mparametros.o mmpi.o

mmontecarlo.o: mmontecarlo.f90 mparametros.o mconfiguraciones.o mtipos.o msteps.o mwavef.o msistref.o mkp_heco.o mdensidades.o mimagina.o mmcvpromedia.o mdmcpromedia.o mrandom.o mmpi.o

mminimiza.o: mminimiza.f90 mmontecarlo.o mentradatos.o mparametros.o mmpi.o

msteps.o: msteps.f90 mparametros.o mtipos.o mrandom.o mwavef.o mrotaciones.o mmcvpromedia.o

mwavef.o: mwavef.f90 mparametros.o mtipos.o mangwavef.o mrotaciones.o msistref.o mvaziz.o mvmolecula.o mlineal.o

mangwavef.o: mangwavef.f90 mparametros.o mtipos.o mlegendre.o

mimagina.o: mimagina.f90 mtipos.o mlegendre.o

mrotaciones.o: mrotaciones.f90 mtipos.o

msistref.o: msistref.f90 mparametros.o mtipos.o

mmcvpromedia.o: mmcvpromedia.f90 mtipos.o mdensidades.o

mdmcpromedia.o: mdmcpromedia.f90 mtipos.o

mdensidades.o: mdensidades.f90 msistref.o mparametros.o mtipos.o

mentradatos.o: mentradatos.f90 mparametros.o mvaziz.o bh_heh2m.o pw_heocs.o mhh_heocs.o mkp_heco.o mrandom.o

mconfiguraciones.o: mconfiguraciones.f90 mrandom.o

mparametros.o: mparametros.f90

mrandom.o: mrandom.f90 mrandom2.o

mrandom2.o: mrandom2.f90

mtipos.o: mtipos.f90

mvaziz.o: mvaziz.f90

mvmolecula.o: mvmolecula.f90 bh_heh2m.o pw_heocs.o mhh_heocs.o mkp_heco.o

bh_heh2m.o: bh_heh2m.f

pw_heocs.o: pw_heocs.f

mhh_heocs.o: mhh_heocs.f90 modlegendre.o

mkp_heco.o: mkp_heco.f90 kpcoef.o

kpcoef.o: kpcoef.f
	$(FC) $(FFLAGS) -c $< $(LDFLAGS)

mlineal.o: mlineal.f90

mlegendre.o: mlegendre.f90

modlegendre.o: modlegendre.f

mmpi.o: mmpi.f90 mtipos.o mrandom.o mrandom2.o mvaziz.o mvmolecula.o mparametros.o
	$(FC) $(FFLAGS) -c $< $(MPILIBS)

